enum ActionTypes {
  START_FETCH_MOVIES = 'START_FETCH_MOVIES',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL',
  SET_SORT_BY = 'SET_SORT_BY',
  SET_FILTER = 'SET_FILTER',
  SET_SEARCH = 'SET_SEARCH',
}

export default ActionTypes;
